### ISSUE TITLE
[custom-element-jsx-integration] export a type of component properties

### ISSUE THREAD

**Issue by odanado** [break-stuff/cem-tools#109]
In the typedef file generated by custom-element-jsx-integration, the types of the component's properties are not exported.
https://github.com/break-stuff/cem-tools/blob/691a720dc392b3bb22a3f1661a0cfa9b61d0ca2f/packages/jsx-integration/src/type-generator.ts#L143

The types of component properties can be used for example in Storybook.

```ts
// Button.stories.ts

import type { Meta, StoryObj } from '@storybook/web-components';
import { Button } from './Button';

// I want to use auto-generated types here.
type ButtonProps = {
  primary: boolean;
}

const meta = {
  title: 'Example/Button',
} satisfies Meta<ButtonProps>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Primary: Story = {
  args: {
    primary: true,
  },
};
```

**Comment by break-stuff** [comment]
We should be able to do that.

As a side note, if you haven't seen it already, I have a set of Storybook helpers for web component integration.

https://www.npmjs.com/package/wc-storybook-helpers

**Comment by odanado** [comment]
I didn't know about `wc-storybook-helpers`. Thank you!

**Comment by break-stuff** [comment]
What are you using to build your components?

As a side note - `title` and `dir` are valid properties for your component types because custom elements extend `HTMLElement` where those properties exist.

**Comment by odanado** [comment]
I use `lit`.

> As a side note - title and dir are valid properties for your component types because custom elements extend HTMLElement where those properties exist.

Yes, I understand this.

However, since the component developer is only interested in the Props of the component, I think it would be ideal if `title` and `dir` were not suggested to reduce noise.
