### ISSUE TITLE
feat: ability to suppresses unimportant logs

### ISSUE THREAD

**Issue by maxpatiiuk** [break-stuff/cem-tools#112]
When using custom-elements-manifests plugin as part of a Vite build process, Vite build output is generally far more important than the output from custom-elements-manifests plugins. Yet, several custom-elements-manifests output excessive and colorful log messages that add noise:

```ts
[vs-code-custom-data-generator] - Generating config files...
[vs-code-custom-data-generator] - Generated "dist/vscode.html-custom-data.json", "dist/vscode.css-custom-data.json".
[vs-code-custom-data-generator] - File generation complete.
[jet-brains-web-type-generator] - Generating config files...
[jet-brains-web-type-generator] - Generated "dist/web-types.json".
[jet-brains-web-type-generator] - File generation complete.
[jsx-type-generator] - Generating types...
[jsx-type-generator] - Generated "dist/custom-element-jsx.d.ts".
[jsx-type-generator] - Type generation complete.
```

![Screenshot 2024-05-05 at 19 21 42](https://github.com/break-stuff/cem-tools/assets/40512816/53734ba0-ac79-4351-a6f5-40305d88655b)

The fact that there are 3 messages per each plugin, and that these messages are using colors makes them stand out too much. These log messages are very much unimportant compared to other build output

Would it be possible to add an option to suppresses log output (except for warnings and errors)? Or at least reduce the log output to just one line rather than 3

Thanks

## Workarounds

Otherwise my solution would have to be to wrap each of the cem hooks these plugins register in a function that will overwrite console.log, and then return it back

**Comment by break-stuff** [comment]
I don't think they're unimportant. 😉

I think we should be able to add an option to suppress logs

**Comment by break-stuff** [comment]
The `hideLogs` configuration has been added to all projects. Let me know if you run into any issues.
