### ISSUE TITLE
bug(custom-element-jsx-integration): incorrect event casing conversion

### ISSUE THREAD

**Issue by maxpatiiuk** [break-stuff/cem-tools#130]
When given a web component that emits an event like `arcgisClick`, in Preact and React 19+ you have to use an `onarcgisClick` prop to listen to such event (the casing must match exactly - no case conversion, only `on` prepended on the front)

However, the types generated by custom-element-jsx-integration are incorrect. They generate an `onArcgisclick` prop.

See React 19 source code:
https://github.com/facebook/react/blob/4fdbac075fd1e804080068b3fd0e86528bf1c9b0/packages/react-dom-bindings/src/client/DOMPropertyOperations.js#L196

See Preact source code:
https://github.com/preactjs/preact/blob/f3edc902447dae7393de7fccaff3b722dee79467/src/diff/props.js#L77

Relevant code in custom-element-jsx-integration:
https://github.com/break-stuff/cem-tools/blob/41098510e6a43d65a9f338761073dbe7ea00ad68/packages/jsx-integration/src/type-generator.ts#L192-L192
https://github.com/break-stuff/cem-tools/blob/41098510e6a43d65a9f338761073dbe7ea00ad68/tools/utilities/src/utilities.ts#L32

**Comment by break-stuff** [comment]
I wonder why React is doing that. It seems like a bug and doesn't follow other event naming conventions. Preact expects [camel-case event names](https://preactjs.com/guide/v10/web-components/#triggering-custom-events) and so does [Stencil](https://stenciljs.com/docs/events#using-events-in-jsx).

**Comment by break-stuff** [comment]
Ah, I see what's happening. This should be pretty easy to patch. Thank you for bringing this to my attention!
