### ISSUE TITLE
Event listener may not be added

### ISSUE THREAD

**Issue by fcollonval** [break-stuff/cem-tools#140]
The `ref` object in the wrapped component is always defined but the `ref.current` may change at a later time.

Therefore that line is erroneous as the effect won't be retriggered when `targetElement.current` changes:

https://github.com/break-stuff/cem-tools/blob/870dc63dbdd72df17d8a09ec68b9d63a94a5e491/packages/react-wrappers/src/utils.ts#L137

should be

```js
   }, [eventName, eventHandler, targetElement.current]); 
```

**Comment by break-stuff** [comment]
Can you provide an example of when it would change?

**Comment by fcollonval** [comment]
This is the default behavior: https://react.dev/reference/react/useRef#useref

In the generated react component, the ref is initialized with `ref.current = null` at

https://github.com/break-stuff/cem-tools/blob/870dc63dbdd72df17d8a09ec68b9d63a94a5e491/packages/react-wrappers/src/wrapper-generator.ts#L354

Then the `useEventListener` is called with `targetElement = ref`. But `ref.current` may still be null so event listener may not be added.

Then react is rendering the component. `ref.current` becomes non-null but the `useEffect` in `useEventListener` is not re executed as `ref` did not change - only `ref.current`.

---

I tried to create a reproducer. But failed to do so easily. It may be less likely in react production mode than in dev mode.

**Comment by break-stuff** [comment]
There should always be a custom element within the wrapper when this code gets executed and it really shouldn't change at any point, so I'm not sure what the issue you are running into is. 

Are you seeing instances where the underlying component is changing and it causing problems or is this a hypothetical scenario where you are trying to identify a potential issue?

**Comment by fcollonval** [comment]
> Are you seeing instances where the underlying component is changing and it causing problems or is this a hypothetical scenario where you are trying to identify a potential issue?

I saw it and pushed the change in [that project](https://github.com/jupyterlab-contrib/jupyter-ui-toolkit/pull/112). The bug appear for me on that wrapped component:

https://github.com/jupyterlab-contrib/jupyter-ui-toolkit/blob/e7ba95ec0aea529e06224b64964744d8fcb80cb7/packages/lab-example/src/index.tsx#L460

The event listeners were not triggered prior to the fix.

**Comment by fcollonval** [comment]
> There should always be a custom element within the wrapper

Yes but you don't control when React is updating `ref.current`, do you?

**Comment by break-stuff** [comment]
It actually should be bound as soon as the element is rendered and the internal element should never change, so there shouldn't be an instance where that ref or event is not bound to the custom element.

We use this in our component library and I don't believe we have run into an issue with this yet.

**Comment by break-stuff** [comment]
a patch for this is included in release 1.6.7.
