### ISSUE TITLE
bug(JetBrains): referenceTemplate argument is ignorred

### ISSUE THREAD

**Issue by maxpatiiuk** [break-stuff/cem-tools#141]
If the `referenceTemplate` option is provided to the `custom-element-jet-brains-integration` plugin, it has no effect.

`getTagList` is called here and given options

https://github.com/break-stuff/cem-tools/blob/870dc63dbdd72df17d8a09ec68b9d63a94a5e491/packages/jet-brains-integration/src/web-types-generator.ts#L154

But `getTagList` itself doesn't look for `referenceTemplate` in options and instead seems to be expect a separate parameter?

https://github.com/break-stuff/cem-tools/blob/870dc63dbdd72df17d8a09ec68b9d63a94a5e491/packages/jet-brains-integration/src/web-types-generator.ts#L37-L40

**Comment by break-stuff** [comment]
Thank you for calling this out!
