### ISSUE TITLE
feat: Do not automatically output the file

### ISSUE THREAD

**Issue by maxpatiiuk** [break-stuff/cem-tools#142]
I would like to call `generateVsCodeCustomElementData()` and `generateJetBrainsWebTypes()` and receive a JSON object in response, rather than have a file written to the disk.

Would it be possible to update the API or provide a different API? Current API assumes that writing to disk right away using sync fs is the only use case.

More on my use case:
- I will write the file to disk on my own at a later stage of my build pipeline, and will use async fs for that
- Or to be clear, Vite will do the writing - they don't like when you emit the file on your own as that interferes with their processes. For example, I need to run `generateVsCodeCustomElementData()` during the `transform()` Vite hook, which is before Vite cleans up the output folder. That means the file that `generateVsCodeCustomElementData()` writes to the disk is deleted - so I must redundantly read it after it's written and write it back after Vite is done writing files. It would be much nicer if `generateVsCodeCustomElementData()` allowed me to write the file on my own terms when I desire.

**Comment by break-stuff** [comment]
How are you generating your CEM?

**Comment by maxpatiiuk** [comment]
I am calling CEM's JavaScript API as part of the `transform()` stage of my Vite plugin:

```ts
import { create } from "@custom-elements-manifest/analyzer/src/browser-entrypoint.js";
create({ modules: [...], plugins: [..., ]})
```

(I need the manifest to inform the transformation)

Later in the pipeline I call cem-tools plugins:

```ts
import { generateVsCodeCustomElementData } from "custom-element-vs-code-integration";
import { generateJetBrainsWebTypes } from "custom-element-jet-brains-integration";

      const silenceLogOutput = vsCode?.hideLogs !== false && jetBrains?.hideLogs !== false;
      const originalConsoleLog = console.log;
      if (silenceLogOutput) {
        console.log = (): void => undefined;
      }
      try {
        generateVsCodeCustomElementData(fullerManifest, {
          hideLogs: true,
          ...vsCode,
          outdir: relativeOutputDir,
          htmlFileName: outputFileNames.vsCodeHtml,
          cssFileName: outputFileNames.vsCodeCss,
        });

        generateJetBrainsWebTypes(fullerManifest, {
          hideLogs: true,
          ...jetBrains,
          outdir: relativeOutputDir,
          webTypesFileName: outputFileNames.webTypes,
        });
      } finally {
        if (silenceLogOutput) {
          console.log = originalConsoleLog;
        }
      }
```

**Comment by maxpatiiuk** [comment]
Another use case:
- I am snapshot-testing the output of my plugin. Because generateJetBrainsWebTypes writes directly to disk, that becomes harder. For example, generateJetBrainsWebTypes reads my package.json to get the version number and puts that into the .json file - that makes the snapshot test brutal - if instead generateJetBrainsWebTypes just returned me a json object, I could easily replace the version number with a stable one and then feed the output to my snapshot test

**Comment by maxicasa** [comment]
Another use case, when use the plugin with storybook and web components. In this case the plugin create a "loop" with vite/storybook watch because (I think) the plugin write the file on the disk and not create a "virtual file" as [vite-plugin-cem](https://github.com/Kamiapp-fr/vite-plugin-cem): 
![image](https://github.com/break-stuff/cem-tools/assets/2181924/df241344-cd00-4f6e-9cfc-fb82ac281fff)

My workaround is temporary remove the plugin during `development`:
```ts
import { customElementVsCodePlugin } from 'custom-element-vs-code-integration';
import { fileURLToPath } from 'node:url';

const outDir = fileURLToPath(new URL('build/library', import.meta.url));

const isProd = process.env.NODE_ENV !== 'development';
const plugins = [];

// Prevent loop with the storybook watch during development
if (isProd) {
  plugins.push(
    customElementVsCodePlugin({
      outdir: outDir,
      typesSrc: 'expandedType'
    })
  );
}

export default {
  /** Globs to analyze */
  globs: ['src/**/*.ts'],

  /** Enable special handling for litelement */
  litelement: true,

  /** Provide custom plugins */
  plugins
};

```

**Comment by break-stuff** [comment]
In this case you could use the `skip` option to prevent it from running in non-build scenarios.

**Comment by maxicasa** [comment]
@break-stuff thanks for the suggestion, I hadn't noticed the option. It's a possible solution for my case but I think the best solution is the suggestion of @maxpatiiuk, allows me to write the file on my own terms if I want.

**Comment by break-stuff** [comment]
With this latest release, you can now use the following methods to generate the file contents:

- VS Code: `getVsCodeHtmlCustomData(manifest, options)` and `getVsCodeCssCustomData(manifest, options)`
- JetBrains: `getWebTypesData(manifest, options)`
