### ISSUE TITLE
Event names conversion react wrappers

### ISSUE THREAD

**Issue by venkatesh-nagineni** [break-stuff/cem-tools#144]
testing custom-element-react-wrappers and working great except event names defined as `myCustomEvent` and this is converted after react generate like` onMycustomevent ` (expected to have`onMyCustomEvent`), actually this could be breaking change for my react consumers that change this structure, if i change my event names like `my-custom-event` then it breaks other non react consumers

is there any option to keep like what stencil-react wrapper is doing

**Comment by break-stuff** [comment]
Yeah, that makes sense. I think we should be able to adjust for that.

**Comment by break-stuff** [comment]
Release 1.6.5 fixes this issue and should be available now.

**Comment by break-stuff** [comment]
Closing, but please let me know if you run into any issues.
