### ISSUE TITLE
Bug: Treeshaking not wroking

### ISSUE THREAD

**Issue by venkatesh-nagineni** [break-stuff/cem-tools#146]
I am testing react wrapper with my stencil components where i have generated components like this

```
import { generateReactWrappers } from "custom-element-react-wrappers";
import manifest from "../custom-data/custom-elements.json" assert { type: "json" };

generateReactWrappers(manifest,
    {
        outdir: 'wrappers/react/dist/',
        modulePath: (className, tagName) => `@lib/my-components/dist/components/${tagName}.js`,
        defaultExport: true,
    });
```

and in my stencil config have dist custom elements like

```
        {
            type: 'dist-custom-elements',
            externalRuntime: false, // https://github.com/ionic-team/stencil/issues/5596#issuecomment-2058481138
        },
```

in react project, i am using only button component but when browser render all my components

does anything wrong i am doing here or it's something we need to take care
![Screenshot 2024-07-18 at 15 18 29](https://github.com/user-attachments/assets/c3246e54-7c74-46cb-ae67-b31630e80287)
![Screenshot 2024-07-18 at 15 18 52](https://github.com/user-attachments/assets/ffaaa33c-bf33-4bce-b2d5-d29408bbe73d)

**Comment by break-stuff** [comment]
The `index.js` file exports all of the components. When you do your final build, only the used modules _should_ be included in the final output. If that doesn't work, you can always import the components individually:

```js
import { Button } from 'path/to/react/Button.js';
import { Dialog } from 'path/to/react/Dialog.js';
```

Instead of:

```js 
import { Button, Dialog } from 'path/to/react';
```
