### ISSUE TITLE
Jetbrains plugin not working

### ISSUE THREAD

**Issue by stevenkuster** [break-stuff/cem-tools#15]
Hi, I would love to get some help with the `customElementJetBrainsPlugin`. We  use the following config to create a web-types.json and a vscode.html-custom-data.json:

```
const options = {
  /** The property form your CEM component object to display your types */
  typesSrc: "expandedType",
}

export default {
  /** Globs to analyze */
  globs: ["src/**/*.ts"],
  ...
  /** Enable special handling for litelement */
  litelement: true,
  ...
  plugins: [
    expandTypesPlugin(),
    customElementVsCodePlugin(options),
    customElementJetBrainsPlugin(options),
  ],
};
```

The `custom-elements.json` gets generated fine with the correct `expandedType` field set to the correct values. For example:
```
{
  "kind": "field",
  "name": "size",
  "type": {
    "text": "ButtonSize"
  },
  "description": "Change the size of the button",
  "default": "medium",
  "attribute": "size",
  "expandedType": {
    "text": "small | medium | large"
  }
},
```

However, when we generate the web-types.json the intellisense of the size attribute doesn't work in IntelliJ even though the corresponding code in the json file looks correct.
```
{
    ...
    "js": {
        "properties": [
              ...
              {
                "name": "size",
                "description": "Change the size of the button",
                "value": { "type": "small | medium | large" }
              },
              ...
         ]
    }
}
```
For reference, the vscode one works just fine. Any help would be greatly appreciated!

**Comment by break-stuff** [comment]
Sure! Let me take a look. Are you working on the latest version?

**Comment by stevenkuster** [comment]
Awesome, thanks. Yes, we are on version `1.2.1`. We did some digging and it looks like the problem might be in the `setEnumTypes` function in the `expandedTypes` plugin. I changed it to a template literal.
```
const shortText = node.members
  ?.map((mem) => `'${mem.initializer?.text}'`)
  .join(" | ");
```
And then in the `updateExpandedTypes` function I added this:
```
member[propName] = {
    text: typeValue,
};
member.type.text = typeValue; // <-- this line is added
```
That seems to fix it for our usecase but I'm not sure what impact that would have for others.

**Comment by break-stuff** [comment]
It looks like that added line overrides the original type text, is that correct?

**Comment by stevenkuster** [comment]
Yes, correct. It was really meant as a workaround. So it's probably not the correct solution.

**Comment by break-stuff** [comment]
Ok, thanks! I will also see if I can get the permissions changed so you can create a PR.

**Comment by break-stuff** [comment]
Thank you, again @stevenkuster, for catching this. The fix was included in release 1.3.0. #20

Let me know if you run into any other issues.

**Comment by break-stuff** [comment]
Sorry, re-opening so you can review before closing.

**Comment by stevenkuster** [comment]
Thanks for the work! And sorry for the late response.

I tried out the new version and it looks like it doesn't fix the problem unfortunately. I think it is due to me using an enum.

For example this doesn't work:
```
enum ButtonSize {
  small = "small",
  medium = "medium",
  large = "large",
}
...
@property() size: ButtonSize = ButtonSize.medium;
```

Whereas this does work:
```
const ButtonSize = {
  small: "small",
  medium: "medium",
  large: "large",
} as const;

type ButtonSizeType = (typeof ButtonSize)[keyof typeof ButtonSize];
...
@property() size: ButtonSizeType = ButtonSize.medium;
```

**Comment by break-stuff** [comment]
Oh, I see. You are correct. You will need to map it like this in order to generate the correct type. The plugin will not map it for you.
