### ISSUE TITLE
suggest to add a default value field to the value object

### ISSUE THREAD

**Issue by wangjiecamen** [break-stuff/cem-tools#16]
suggest to add a default value field to the value object in function of generateJetBrainsWebTypes

```json
 {
              "name": "target",
              "description": "'_blank' | '_parent' | '_self' | '_top' | ''",
              "value": { "type": "string" }
  }
```
to : 

```json
 {
              "name": "target",
              "description": "'_blank' | '_parent' | '_self' | '_top' | ''",
              "value": { "type": "string" , default : "_blank"}
  }
```

**Comment by break-stuff** [comment]
I think we should be able to add this. Thanks for the suggestion!

**Comment by wangjiecamen** [comment]
> I think we should be able to add this. Thanks for the suggestion!

You are welcome! But another question,how to generate slot object in web-types.json.I try to set @slot in jsdoc,then i found its added to description(include event) and no slot object:
``` json
 "description": "This is MyElement\n---\n\n\n### **Events:**\n - **load** - some description for load\n\n### **Slots:**\n - **image** - This is a default/unnamed slot",
```

**Comment by wangjiecamen** [comment]
> Is there a slot option in the web-types API?

sure 
<img width="699" alt="image" src="https://github.com/break-stuff/cem-tools/assets/43318581/91cb6768-b881-49da-9260-2eb3f37ae283">

**Comment by break-stuff** [comment]
Slots and default values were just deployed in 1.3.0. #20

Thank you, again @wangjiecamen, for the great suggestions!

**Comment by break-stuff** [comment]
Sorry, re-opening so you can review before closing.

**Comment by wangjiecamen** [comment]
thank you !
