### ISSUE TITLE
Request to decouple file generation and package.json updates

### ISSUE THREAD

**Issue by claviska** [break-stuff/cem-tools#22]
Love the VS Code and JetBrains plugins!

One request — can we make writing the property to `package.json` optional? I imagine it's a one-time thing for most users to add it. The reason for this request is we keep seeing changes like this:

![CleanShot 2023-10-26 at 10 41 20@2x](https://github.com/break-stuff/cem-tools/assets/55639/2aba646a-c344-46bd-8302-bca2c3508575)

It's caused by differences in how npm and this plugin stringify JSON data.

https://github.com/break-stuff/cem-tools/blob/c0765b9f49734a807a3243247c891d521ed8006b/packages/jet-brains-integration/src/web-types-generator.ts#L175

Every time we run an npm command that updates `package.json`, it gets formatted the npm way. Then when we run the build, it gets formatted another way, resulting in noisy whitespace commits (or us having to manually revert them).

I'm not sure if this affects all plugins in this repo, but we use the VS Code and JetBrains ones and both of those exhibit the same behavior.

Thanks!

**Comment by break-stuff** [comment]
Sure! I think that can be added as an option.

**Comment by break-stuff** [comment]
The option is deployed in release 1.4.0 (#24). Let me know if you run into any issues with it.
