### ISSUE TITLE
custom-element-vs-code-integration: order of elements changes, when nothing else has been changed

### ISSUE THREAD

**Issue by herrKlein** [break-stuff/cem-tools#32]
When running the analyzer with custom-element-vs-code-integration

the generated file is different then the previouse version due to re-ordering of elements in this file.
Although nothing really has changed.

This causes too many commits and changes
```
vscode.html-custom-data.json
```

**Comment by break-stuff** [comment]
Is the order changing in the CEM?

**Comment by herrKlein** [comment]
Yes looks like it does, so thats the problem..
You can close this issue then, I removed the generated vscode custom files from the repository, I already did that for the custom-element.json, so thats why it did not change for me when comitting

**Comment by break-stuff** [comment]
Yeah, I have seen that happen before too. No problem!

**Comment by esteinborn** [comment]
Sorry to resurrect an old thread but I am having difficulty with CEM generating a different order of my elements on each compile. 

Without changing anything running `npm run cem analyze` twice causes the generated custom-elements-manifest.json to order the list of custom elements seemingly randomly. 

Any ideas on what could be causing this to generate a unique file each time and now be based off the order it wants? 

I'd like to get to a point where running the `cem analyze` command will generate the same file each time so I don't have to mess around with git commits every time I generate the file. 


Does this have anything to do with globbing the files? Would it be better to list out each file separately in order for it to generate the same each time?
`globs: ["**/packages/**/*.ts"],`

Thanks for any help you can provide!

**Comment by break-stuff** [comment]
@herrKlein and @esteinborn  Here is a plugin I created to help generate consistent results every time. Let me know if this helps.

https://wc-toolkit.com/cem-utilities/cem-sorter/

**Comment by esteinborn** [comment]
Thanks for this, I'll check it out. We found a way to do it this way as well:

```js
  plugins: [
    {
      name: "nysds-sorter",
      packageLinkPhase({ customElementsManifest }) {
        // Sort top-level modules
        customElementsManifest.modules.sort((a, b) =>
          a.path.localeCompare(b.path)
        );

        for (const mod of customElementsManifest.modules) {
          if (mod.declarations) {
            mod.declarations.sort((a, b) =>
              (a.name || "").localeCompare(b.name || "")
            );
          }

          if (mod.exports) {
            mod.exports.sort((a, b) =>
              (a.name || "").localeCompare(b.name || "")
            );
          }
        }
      }
    },
```
