### ISSUE TITLE
custom-element-react-wrappers: the exclude property does not exclude

### ISSUE THREAD

**Issue by herrKlein** [break-stuff/cem-tools#33]
I just converted from from the cem-react wrapper plugin, 

There is also an exclude property in that library, 
In the old library the classes were nicely excluded, in the new they are not.

It would also be nice to have an include property. I just want some elements wrapped. Most elements are just intrinsic elements. So now whenever I have a new element, which I don't want to be wrapped, I have to put it in the exclude list.

**Comment by break-stuff** [comment]
Yep! I see the problem and will get a fix out soon. Thank you!

**Comment by break-stuff** [comment]
The fix for this was just deployed in 1.0.5 (#36). Let me know if you run into any issues.

**Comment by break-stuff** [comment]
I'm going to close this. Let me know if you run into any other issues.
