### ISSUE TITLE
[React Wrappers]  React events are bound late, connectedCallback and firstUpdated are already dispatched

### ISSUE THREAD

**Issue by herrKlein** [break-stuff/cem-tools#34]
I posted this in the old CEM repository, but after testing I noticed the same problem occurs in this repository

I generated react wrappers
And when I attach a listener, which awaits an event directly from the original component on connectedCallback or firstUpdated it is not catched.

```jsx
<QtiAssessmentItemRef onQtieItemConnectedCallback={(event) => { console.log('late to the party' }}>
</QtiAssessmentItemRef>
```

I debugged this code and the component, and the components lifecycle already travelled connectedCallback and firstUpdated before the eventlistener is attached in the below code:

react-utils.js
```js
export function useEventListener(targetElement, eventName, eventHandler) {
  useEffect(() => {
    if (eventHandler !== undefined) {
      targetElement?.current?.addEventListener(eventName, eventHandler);
    }

    return () => {
      if (eventHandler?.cancel) {
        eventHandler.cancel();
      }

      targetElement?.current?.removeEventListener(eventName, eventHandler);
    };
  }, [eventName, eventHandler, targetElement]);
}
```

**Comment by break-stuff** [comment]
Thanks! I believe updating this to use `useLayoutEffect` should add the listener sooner. I will get an update out.

**Comment by break-stuff** [comment]
I deployed this fix in 1.0.5 (#36). Let me know if you still run into any issues.

**Comment by herrKlein** [comment]
Hi, I had some time to test this. It was missing the import of useLayoutEffect, so I added that in a pull request.

**Comment by break-stuff** [comment]
Awesome! Thank you!

**Comment by break-stuff** [comment]
I deployed 1.1.0 that includes your fix as well as an update to use `useLayoutEffect` for attributes as well. I tried using it for properties, but it was logging an error because the component is `undefined`.

**Comment by break-stuff** [comment]
Additional updates for this have been deployed in release 1.2.0 (https://github.com/break-stuff/cem-tools/pull/67). Let me know if you run into any issues.

**Comment by break-stuff** [comment]
Closing this for now. Let me know if you run into any issues.
