### ISSUE TITLE
custom-element-react-wrappers: When using the key prop on an element this error occurs

### ISSUE THREAD

**Issue by herrKlein** [break-stuff/cem-tools#35]
When adding this key prop JSX throws an error
```key={item.vertaling}```

I used the same key prop with the old `[cem-plugin-react-wrapper](https://github.com/break-stuff/cem-plugin-react-wrapper)` and then it did not throw an error

![Screenshot 2023-11-21 at 16 45 54](https://github.com/break-stuff/cem-tools/assets/6085660/5c0298b5-5b31-40af-b1fe-b82b63585f48)

Usage:
```js
{vervoegingen.map(item => (
  <QtiAssessmentItemRef key={item.vertaling} onQtieItemConnectedCallback={({ target: itemRef }: { target: QtiAssessmentItemRefElement }) => {
  }}
  identifier={item.vertaling} href={item.vertaling}>
  </QtiAssessmentItemRef>
))}
```

**Comment by break-stuff** [comment]
When you look in the generated types for that component, do you see `key` listed among the props?

**Comment by herrKlein** [comment]
Ignore this issue, I think I introduced while thinkering in the node_modules folder with the generated react types to find out why other things were not working. sorry for the inconvenience
