### ISSUE TITLE
custom-element-react-wrappers: config.attributeMapping undefined even though it was set in the config

### ISSUE THREAD

**Issue by stevenkuster** [break-stuff/cem-tools#44]
I'm trying to use the `customElementReactWrapperPlugin` to create react wrappers but I'm running into the issue that the `attributeMapping` I defined in my config is undefined when I run my build.

My setup looks like this:
``` ts
    customElementReactWrapperPlugin({
      modulePath: (_, tagName) => getComponentsPath(tagName),
      outdir: `dist/react`,
      attributeMapping: {
        for: "_for",
      },
    })
```

The error I get:
```
 TypeError: Cannot use 'in' operator to search for 'for' in undefined
    at [obfuscated-path]/node_modules/.pnpm/custom-element-react-wrappers@1.0.6/node_modules/custom-element-react-wrappers/dist/index.js:507:21
```

Which leads me to this part of the code:
```
    if (RESERVED_WORDS.includes(attr?.name)) {
      if (attr.name in config.attributeMapping) {
        const attribute = getMappedAttribute(attr);
        addAttribute(attribute, result);
        return;
      }
      throwKeywordException(attr, component);
    }
```

When I log `config` there I get:
```
{
  outdir: 'dist/react',
  exclude: [],
  typesSrc: 'types',
  modulePath: [Function: modulePath]
}
```
As you can see the `attributeMapping` I defined is missing here which results in my build failing. Am I missing something here in my config? Or is this a bug perhaps?

**Comment by break-stuff** [comment]
Thank you! I will take a look at it now.

**Comment by break-stuff** [comment]
I just deployed 1.1.0. Let me know if you run into any issues.

**Comment by stevenkuster** [comment]
Works like a charm. Thanks for the quick fix!

**Comment by break-stuff** [comment]
Awesome! Thank you for letting me know!
