### ISSUE TITLE
[Custom Element VS Code Integration] `descriptionSrc` configuration docs

### ISSUE THREAD

**Issue by arieffikhrie** [break-stuff/cem-tools#81]
I have CEM file that in the module it do have another custom properties that i added as part of description, so i need to use specific property for it, in the README file on this `vs-code-integration` package, https://github.com/break-stuff/cem-tools/blob/94d8a4fb87e08f55a9d4eef71b28bf514f366899/packages/vs-code-integration/README.md?plain=1#L100

it does have the options for the `descriptionSrc` and it does show the type of `"description" | "summary" | string`, but it actually only accept "description" | "summary", based on this base type

https://github.com/break-stuff/cem-tools/blob/94d8a4fb87e08f55a9d4eef71b28bf514f366899/tools/configurations/src/config.ts#L7

So it would return typescript error that it does not allow any string property that i want to use.

Can you update the type to be something like this

```ts
export interface BaseOptions {
  // ...
  /** The property name from the component object that you would like to use for the description of your component */
  descriptionSrc?: "description" | "summary" | ( string & {}) ;
```

or you can take a look on the `type-fest` package on `LiteraUnion` https://github.com/sindresorhus/type-fest/blob/main/source/literal-union.d.ts

**Comment by break-stuff** [comment]
I just deployed a change for this. Let me know if you run into any issues.

**Comment by arieffikhrie** [comment]
It works now, thanks, no more @ts-ignore for me 😅
