### ISSUE TITLE
[jet-brains-integration] feature request, option to set the default-icon for web-types.json

### ISSUE THREAD

**Issue by veith** [break-stuff/cem-tools#99]
Displaying your icon on the code completion list in intellij is a nice feature.

**Comment by break-stuff** [comment]
I didn't know this was a feature. Can you provide an example of what it does exactly?

**Comment by veith** [comment]
And if you just type something like "card" they are mixed together.

<img width="382" alt="Screenshot 2024-03-08 at 13 49 07" src="https://github.com/break-stuff/cem-tools/assets/606760/deeb6a45-ee0c-4d4f-bccc-f89d327b0586">

**Comment by break-stuff** [comment]
Oh, that's really nice!
